# VATEX-EVAL VCS Evaluation Configuration
# Configuration for comprehensive VCS evaluation with multiple chunk sizes and LCT values

# ============================================================================
# ESSENTIAL PATHS (MUST BE UPDATED FOR YOUR ENVIRONMENT)
# ============================================================================
models:
  # Path to downloaded NV-Embed model directory
  # Download from: https://huggingface.co/nvidia/NV-Embed-v1
  nv_embed_path: "/mmfs1/scratch/jacks.local/mali9292/VAD-LLM2Vec/nv-embed"

# ============================================================================
# DATA AND OUTPUT PATHS
# ============================================================================
paths:
  # Base output directory for results
  results_dir: "/mmfs1/scratch/jacks.local/mali9292/Video-Comprehension-Score/exp/results/vatex-eval"
  
  # Logs directory (relative to script location)
  logs_dir: "logs"

# ============================================================================
# VATEX-EVAL SPECIFIC SETTINGS
# ============================================================================
vatex_eval:
  # Path to VATEX-EVAL JSON data file
  data_dir: "/mmfs1/scratch/jacks.local/mali9292/Video-Comprehension-Score/exp/data/vatex-eval/vid_cans_score_dict.json"
  
  # Number of references to use for evaluation (list of integers)
  # Each value will be evaluated separately
  use_n_refs: [1, 9]
  
  # Segmenter function: uses segmenter_punc_stop with NLTK stopwords
  # This is the only supported segmenter for VATEX-EVAL VCS analysis

# ============================================================================
# VCS COMPUTATION SETTINGS
# ============================================================================
vcs:
  # LCT (Line Chronological Tolerance) values to compute
  # LCT = 0: Strict chronological order (DEFAULT)
  # LCT > 0: Allow chronological flexibility
  # Results will include metrics for all combinations: VCS_C{chunk}_LCT{n}
  lct_values: [0, 1]
  
  # Chunk sizes to evaluate (discrete values)
  # Results will include metrics for all combinations: VCS_C{chunk}_LCT{n}
  # Examples:
  #   chunk_size: [1]        # Only chunk size 1
  #   chunk_size: [1, 2]     # Chunk sizes 1 and 2
  #   chunk_size: [1, 2, 3]  # Multiple chunk sizes
  chunk_size: [1]
  
  # VCS algorithm parameters
  context_cutoff_value: 0.6
  context_window_control: 4.0
  
  # Return detailed VCS internals for debugging
  return_all_metrics: true
  return_internals: false

# ============================================================================
# PARALLEL PROCESSING
# ============================================================================
processing:
  # Number of parallel workers for candidate processing
  # Recommendations:
  #   - 1-2 workers: 8GB RAM systems
  #   - 4 workers: 16GB RAM systems  
  #   - 8+ workers: 32GB+ RAM systems
  max_workers: 48
  
  # Checkpoint saving interval (save every N candidates processed)
  checkpoint_interval: 100
  
  # Resume from checkpoint if available
  resume_from_checkpoint: true

# ============================================================================
# OUTPUT FORMATTING
# ============================================================================
output:
  # Decimal precision for metrics
  decimal_precision: 4
  
  # Output options
  save_correlation_summary: true
  save_detailed_scores: true

# ============================================================================
# NEW DIRECTORY STRUCTURE
# ============================================================================
# Results will be organized as follows:
#
# results/vatex-eval/
# ├── individual_results/
# │   ├── 1ref/
# │   │   ├── _2zXAtOKXm0_000004_000014.csv
# │   │   └── [other video CSV files]
# │   └── 9ref/
# │       ├── _2zXAtOKXm0_000004_000014.csv
# │       └── [other video CSV files]
# └── aggregated_results/
#     └── correlation_summary.csv  # Hierarchical format with all n_refs
#
# Individual CSV format:
# candidate_id,candidate,best_score,best_reference,human_score_1,human_score_2,human_score_3,human_avg,VCS_C1_LCT0,VCS_C1_LCT1,VCS_C2_LCT0,VCS_C2_LCT1
#
# Aggregated correlation_summary.csv format:
# Metric,1ref_Kendall_Tau,1ref_Spearman_Correlation,9ref_Kendall_Tau,9ref_Spearman_Correlation

# ============================================================================
# LOGGING AND VERBOSITY
# ============================================================================
logging:
  # Enable verbose output to console
  verbose: false

# ============================================================================
# EXPERIMENT SETTINGS
# ============================================================================
experiment:
  # Custom experiment ID (if empty, auto-generates timestamp)
  experiment_id: ""