# VCS Evaluation Framework Configuration - Addition Experiment
# Only experiment-specific settings (inherits from _base.yaml)

# ============================================================================
# EXPERIMENT SETTINGS
# ============================================================================
experiment:
  # Custom experiment ID (if empty, auto-generates timestamp)
  # Each experiment should have its own ID for parallel execution
  experiment_id: ""

# ============================================================================
# EXPERIMENT-SPECIFIC PATHS
# ============================================================================
paths:
  # Input data directory containing JSON files with iterations
  data_dir: "/mmfs1/scratch/jacks.local/mali9292/Video-Comprehension-Score/exp/data/mpii/addition/aug_dataset"
  
  # Base output directory for results
  results_dir: "/mmfs1/scratch/jacks.local/mali9292/Video-Comprehension-Score/exp/results/mpii/addition"

# ============================================================================
# ADDITION-SPECIFIC EXPERIMENT SETTINGS
# ============================================================================
addition:
  # Subfolders to process in the dataset
  subfolders: ["beginning", "middle", "end", "random"]
  
  # Number of iterations to process per JSON file
  num_iterations: 10
  
  
  # Enable ablation table generation (separate from comparison)
  ablation: true
  
  # Enable comparison table generation (separate from ablation)  
  comparison: true

# ============================================================================
# VCS SETTINGS OVERRIDE
# ============================================================================
vcs:
  # Chunk size for VCS computation (list format for consistency)
  chunk_size: [1]
  
  # For addition experiments, use strict chronological order
  lct: [0, 1]
  
  # Return all metrics for ablation studies
  return_all_metrics: true
  
  # Return similarity values for detailed analysis
  return_similarity_values: true

# ============================================================================
# METRICS CONFIGURATION
# ============================================================================
# Note: Metrics are hardcoded in the script, not read from config
# The metrics section was unused dead code and has been removed

# ============================================================================
# OUTPUT FORMATTING OVERRIDES
# ============================================================================
# Note: decimal_precision is inherited from _base.yaml
# All other output parameters (aggregated_format, save_*, table_format) were unused dead code

# ============================================================================
# LOGGING OVERRIDES
# ============================================================================
# Note: Only logging.verbose is used (via command line --verbose flag)
# Other logging parameters were unused dead code and have been removed

# ============================================================================
# EXPERIMENT SETTINGS OVERRIDE
# ============================================================================
experiment:
  # Experiment type
  type: "addition"