# VCS Evaluation Framework Configuration - Authors Experiments
# Only experiment-specific settings (inherits from _base.yaml)

# ============================================================================
# EXPERIMENT SETTINGS
# ============================================================================
experiment:
  # Custom experiment ID (if empty, auto-generates timestamp)
  # Each experiment should have its own ID for parallel execution
  experiment_id: ""

# ============================================================================
# EXPERIMENT-SPECIFIC PATHS
# ============================================================================
paths:
  # Input data directory containing JSON files
  data_dir: "/mmfs1/scratch/jacks.local/mali9292/Video-Comprehension-Score/exp/data/mpii/authors/aug_dataset_test"
  
  # Base output directory for results
  results_dir: "/mmfs1/scratch/jacks.local/mali9292/Video-Comprehension-Score/exp/results/mpii/authors"

# ============================================================================
# AUTHORS SPECIFIC SETTINGS
# ============================================================================
authors:
  # Author file mappings
  author_files:
    A1: "author1.json"
    A2: "author2.json"
    A3: "author3.json"
    A4: "author4.json"
  
  # Selected metrics to compute
  selected_metrics:
    - "BLEU-1"
    - "BLEU-4"
    - "METEOR"
    - "ROUGE-1"
    - "ROUGE-4"
    - "ROUGE-L"
    - "ROUGE-Lsum"
    - "VCS"

# ============================================================================
# VCS SETTINGS OVERRIDE
# ============================================================================
vcs:
  # Chunk sizes to evaluate (discrete values)
  chunk_size: [1]
  
  # LCT (Line Chronological Tolerance) values to compute
  lct: [0, 1]
  
  # Return all metrics for detailed analysis
  return_all_metrics: true
  
  # Return similarity values for ablation studies
  return_similarity_values: true

# ============================================================================
# EXPERIMENT SETTINGS OVERRIDE
# ============================================================================
# Note: experiment section was duplicated - removed duplicate
# Original experiment section at top of file is sufficient