# VCS Evaluation Framework Configuration - Comparison Experiments
# Only experiment-specific settings (inherits from _base.yaml)

# ============================================================================
# EXPERIMENT SETTINGS
# ============================================================================
experiment:
  # Custom experiment ID (if empty, auto-generates timestamp)
  # Each experiment should have its own ID for parallel execution
  experiment_id: ""

# ============================================================================
# EXPERIMENT-SPECIFIC PATHS
# ============================================================================
paths:
  # Input data directory containing JSON files
  data_dir: "/mmfs1/scratch/jacks.local/mali9292/dev-vcs-vatex/vcs/exp/data/mpii/comparison/aug_dataset"
  
  # Base output directory for results
  results_dir: "/mmfs1/scratch/jacks.local/mali9292/dev-vcs-vatex/vcs/exp/results/mpii/comparison"